services:
  backend:
    build:
      context: .
      dockerfile: local.dockerfile
    restart: unless-stopped
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - '5500:5500'
    env_file:
      - ./.env.development.local
    networks:
      - app-network

  postgres:
    image: postgres:17.6-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    env_file:
      - ./.env.development.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:8.2.1-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
    - app-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - RIPORT=8001
    depends_on:
      - redis
    networks:
      - app-network

volumes:
 redis_data:
 postgres_data:

networks:
  app-network:
    driver: bridge
