services:
  backend:
    build:
      context: .
      dockerfile: local.dockerfile
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - '5500:5500'
    env_file:
      - ./.env.development.local

  redis:
    image: redis:latest
    ports:
      - '6380:6380'
    restart: always
    volumes:
      - redis_data:/data

volumes:
 redis_data:
